import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Mapper;

import java.util.Scanner;
import java.io.IOException;

/**
 * Created by Yuqing Wang on 2017/4/15.
 */
public class OrderHashTagsMapper extends Mapper<LongWritable, Text, LongWritable, Text> {

    /**
     * this method overrides the map method in the Mapper class so that it can read from the temp_output file and switch order of the key(hash tag) and value(hash tag count).
     * @param key the key automatically generated by the hadoop
     * @param value a line of the input file(a key-value pair from the temp_output)
     * @param output the output of the map method
     * @throws IOException when the program fails to produce output
     * @throws InterruptedException when the program fails to produce output
     */
    public void map(LongWritable key, Text value, Context output) throws IOException, InterruptedException {
        String line = value.toString();
        Scanner scanner = new Scanner(line);

        try {
            String tag = scanner.next();
            long tagCount = Long.parseLong(scanner.next());
            output.write(new LongWritable(tagCount), new Text(tag));
        } catch (NumberFormatException e) {
            //when the number format mismatches, this line will be ignored
        }

        scanner.close();
    }
}
